//created on: May 18, 2021
package sbnz.integracija

//list any import classes here.

import sbnz.integracija.example.model.Dish;
import sbnz.integracija.example.model.Restaurant;
import sbnz.integracija.example.model.Price;
import sbnz.integracija.example.model.PriceCategory;

//declare any global variables here




rule "Calculate dish price category, if under average then it is cheap"

    when
        $d : Dish($id : id)
        $r : Restaurant($resId : id)
        $avgPrice : Number() from accumulate(
								Price( dish.id == $id , $pr: price ), 
								average($pr)
							)
		$p : Price(dish.id == $id , restaurant.id == $resId, $price : price )
		eval($price < ($avgPrice.intValue() -50))
    then
        $p.setPriceCategory(PriceCategory.CHEAP);
        update($p);
        System.out.println("Jelo : " + $p.getDish().getId() + " izkategorije : "+ $p.getPriceCategory() + " prosecna cena je : "+ $avgPrice + " cena jela je: " + $price + " iz restorana " + $r.getId());

end


rule "Calculate dish price category, if above average then it is expensive"

    when
        $d : Dish($id : id)
        $r : Restaurant($resId : id)
        $avgPrice : Number() from accumulate(
								Price( dish.id == $id , $pr: price ), 
								average($pr)
							)
		$p : Price(dish.id == $id , restaurant.id == $resId, $price : price )
		eval($price > ($avgPrice.intValue() + 50))
    then
        $p.setPriceCategory(PriceCategory.EXPENSIVE);
        update($p);
        System.out.println("Jelo : " + $p.getDish().getId() + " iz kategorije : "+ $p.getPriceCategory() + " prosecna cena je : "+ $avgPrice + " cena jela je: " + $price + " iz restorana " + $r.getId());
        
end

rule "Calculate dish price category, if in average then it is standard"

    when
        $d : Dish($id : id)
        $r : Restaurant($resId : id)
        $avgPrice : Number() from accumulate(
								Price( dish.id == $id , $pr: price ), 
								average($pr)
							)
		$p : Price(dish.id == $id , restaurant.id == $resId, $price : price )
		eval($price >= ($avgPrice.intValue() - 50) && $price <= ($avgPrice.intValue() + 50))
    then
        $p.setPriceCategory(PriceCategory.STANDARD);
        update($p);
        System.out.println("Jelo : " + $p.getDish().getId() + " iz kategorije : "+ $p.getPriceCategory() + " prosecna cena je : "+ $avgPrice + " cena jela je: " + $price + " iz restorana " + $r.getId());
       
end

